### ISSUE TITLE
watch the recording and go through that website

### ISSUE THREAD

**Issue by JudahGoldstein** [JudahGoldstein/EECS2030A3#2]
- [x]  Judah

- [x] Devin

- [x] Vivaan

https://schemas.liquid-technologies.com/RETS/xsd_20082406/?page=syndication_xsd.html

**Comment by devin-lo** [comment]
**goal:** implement the hierarchy of the properties that an MLS can present

he wants us to generally know what those property types (townhouse, duplex, etc) are (~1 hr of research)

because we need to do CRUD, it sounds like we need to store the entries into something (perhaps that's how we re-use the cache code?), then use getter/setter methods on this data structure for doing CRUD

do not have to use ALL of the fields he listed

we could split it into single-unit structures vs. multi-unit structures ??


### report contents:

UML diagrams, relationships between classes (solid vs hollow diamonds)

explain your design

how we show public vs private methods
how we encapsulate
what is abstraction
why is the class abstract
why is it extended
why using these interfaces
why introduce these exceptions


he said "this assignment is quite liberal" so we can pick and choose what we want to implement??

he showed the class how to create a spring boot project around 1:13:00 of the lecture video
