### ISSUE TITLE
Initial UML 

### ISSUE THREAD

**Issue by JudahGoldstein** [JudahGoldstein/EECS2030A3#4]

**Comment by devin-lo** [comment]
- [x] replicate the Syndication.xml framework in intellij as classes with attributes only (no methods), in order to create a preliminary UML
- [x] double check that all the attributes mentioned in the prof's handout have been covered
the very original draft (with all the hardcoded attributes) has been created already

~~- [ ] look at changing some of the ArrayList<String> attributes into enum type? (should probably do this at the very least for PropertyType and PropertySubType, in order to fulfill the basic requirement of this assignment)~~

**Comment by devin-lo** [comment]
new draft, based on the code judah made, and what i think we need to add to demonstrate course concepts

![Image of a new rough UML](https://media.discordapp.net/attachments/859963004636495894/867662902462382110/unknown.png)

**Comment by devin-lo** [comment]
was redone

**Comment by devin-lo** [comment]
re-exported three different UML pngs earlier
